workflows:
  ios-simulator-workflow:
    name: Build iOS Simulator (for Appetize)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build for iOS simulator
        script: |
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
